services:
  frontend:
    build: ./frontend
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - 5173:5173
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      # Last line has been modified by AI, from :
      # - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      # Last line has been modified by AI from : test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - app_network

networks:
  app_network:
volumes:
  pg_data:
